image: Visual Studio 2017

environment:
    matrix:
        - BUILD_NAME: "MSVS 2017 x64 Release"
          CMAKE_CONFIG_FLAGS: "-G\"Visual Studio 15 2017 Win64\" -DCMAKE_PREFIX_PATH=\"C:/Qt/5.13.0/msvc2017_64/lib/cmake/Qt5\""
          CMAKE_BUILD_FLAGS: "--config Release"
        - BUILD_NAME: "MinGW 7.3.0 x32 Release"
          CMAKE_CONFIG_FLAGS: "-G\"MinGW Makefiles\" -DCMAKE_PREFIX_PATH=\"C:/Qt/5.13.0/mingw73_32/lib/cmake/Qt5\" -DCMAKE_MAKE_PROGRAM=\"mingw32-make.exe\" -DCMAKE_BUILD_TYPE=Release"
          ADDITIONAL_PATH: "C:\\Qt\\Tools\\mingw730_32\\bin"

#install:
#    - set PATH=%ADDITIONAL_PATH%;%PATH%
#    - echo %PATH%

for:
-
    matrix:
        only:
            - BUILD_NAME: "MSVS 2017 x64 Release"

    install:
        - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

-
    matrix:
        only:
            - BUILD_NAME: "MinGW 7.3.0 x32 Release"

    install:
        - set PATH=C:\\Qt\\Tools\\mingw730_32\\bin;%PATH%

build_script:
    - cd build
    - cmake %CMAKE_CONFIG_FLAGS% ..
    - cmake --build . %CMAKE_BUILD_FLAGS%
